name: Jeonguk Han's Homepage 
url: https://jeongukhan.github.io/
description: 밤하늘 관측 / 리눅스 시스템 프로그래밍 / ...

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
